- .gitignore
- META6.json
JSON::Fast is used but not listed as a dependency
> Fix missing JSON::Fast dep & ignore *~ files

- lib/Cro/HTTP/Router.pm6
- t/http-router.t
when we get a request for `/`, we don't want to pass the (useless) positionals from `$args` to `&!implementation` (whose signature won't expect it), but we still need to pass the named parts, otherwise things like:
get -> :$foo! { ... }
will die
> always pass named arguments from capture

- lib/Cro/HTTP/Client/CookieJar.pm6
Flag is used mainly by some browsers to disallow access to cookie through
client side script. More info: https://www.owasp.org/index.php/HttpOnly
> Fix HTTP::Client handling of http-only flag

- lib/Cro/HTTP/Session/Persistent.pm6
- t/http-session-persistent.t
As it becomes useless to keep sessions in database when the cookie
name changes on every application run. Make not setting cookie-name an
error.
> Do not randomize cookie name for persistent role

- lib/Cro/HTTP/Server.pm6
See: https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
This change when implemented on https://myjudo.net took it from a "B" to an "A" on ssllabs:
https://dev.ssllabs.com/ssltest/analyze.html?d=myjudo.net
> Set default ciphers to Moz. Modern Compatibility

- lib/Cro/HTTP/BodyParsers.pm6
- t/http-request-parser.t
Google Chrome produces the following Content-Type:
```
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```
So `eq` fails. I changed this to index, to match from the beggining of
the line
> Fix WWWUrlEncode applicable to not exact match

- lib/Cro/HTTP/Router.pm6
- t/http-router.t
If we are doing request to the root of the static path, indexes going to
be used, but problem here that calculation of the mime-type based on the
root directory extension, instead of extension of the index file.
Test on master and fix branches:
```
master # prove -e 'perl6 -Ilib' t/http-router.t
t/http-router.t .. 349/? # Failed test 'Indexes with mime-types returns proper content-type'
t/http-router.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/388 subtests 
Test Summary Report
-------------------
t/http-router.t (Wstat: 256 Tests: 388 Failed: 1)
Failed test:  388
Non-zero exit status: 1
Files=1, Tests=388, 15 wallclock secs ( 0.06 usr  0.00 sys + 17.86 cusr  0.34 csys = 18.26 CPU)
Result: FAIL
fix-static-indexes # prove -e 'perl6 -Ilib' t/http-router.t
t/http-router.t .. ok …
```
> Fix router indexes + mime-types match

- lib/Cro/HTTP/Server.pm6
Mozilla have updated their TLS recommendations. We can no longer use the "Modern" preset as I don't think we support TLS 1.3 yet, but the "Intermediate" preset is probably a better fit as it's the recommended preset for a general-purpose server. The main change is the dropping of CBC in favour of GCM. This change restores a SSL Labs rating of "A" out of the box.
> Update default TLS cipher list

- lib/Cro/HTTP/Cookie.pm6
- t/http-cookie.t
The SameSite directive can be used to restrict the sending of cookies in
cross-origin requests.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies
There is strong support for SameSite cookies in modern browsers:
https://caniuse.com/#search=samesite
> Add support for SameSite cookie directive

- lib/Cro/HTTP/Log/File.pm6
Log messages should never be trapped in the output buffer. Otherwise they may be written delayed (or - in the case of running in docker - be completely lost). This is severe for log messages.
Why log messages are also buffered when logging to STDOUT/STDERR with a TTY attached is unclear. This might indicate a bug in rakudos TTY detection.
None the less this fix is legit, because even when logging to a file one doesn't want output buffering.
> Make sure logs are written on the spot

- lib/Cro/HTTP2/FrameParser.pm6
- lib/Cro/HTTP2/GeneralParser.pm6
- lib/Cro/HTTP2/RequestSerializer.pm6
- t/http2-request-parser.t
- t/http2-request-serializer.t
- t/http2-response-parser.t
Some servers are more picky than others. This fixes #85 and fixes #45, along with making sure we emit the response object as soon as we have the headers, rather than waiting for the whole body.
> Assorted HTTP/2 fixes

- lib/Cro/HTTP/RawBodyParserSelector.pm6
- t/http-rawbodyparserselector.t
Use Content-Length or otherwise to determine the RawBodyParser as
the 'identity' transfer-encoding implies 'as-is' encoding.
RFC 2616 indicates https://tools.ietf.org/html/rfc2616#section-3.5 that
this SHOULD NOT be used in a Transfer-Encoding header, but there is at
least one library that does emit this (as noted in #89 ,) so it seems
prudent to accept it even if it is non-compliant.
Fixes #89
> Support "Transfer-Encoding: identity"

- lib/Cro/HTTP/Client.pm6
- lib/Cro/HTTP/Server.pm6
Sets the `:nodelay` flag (provided by previous pull requests) when establishing a client connection or setting up a server listener.  This is a win for HTTP connection performance in general, though overhead causes this to be a larger win for TCP than TLS connections.
This is another in the patch series for https://github.com/croservices/cro/issues/129 .
> Turn on TCP_NODELAY for HTTP Client and Server

- lib/Cro/HTTP/Header.pm6
- lib/Cro/HTTP/Message.pm6
- lib/Cro/HTTP/RequestParser.pm6
I looked at a profile of a Cro HTTP application (for no reason other than I was using it to test some tweaks to the profiler in Comma), spotted some things that looked a bit costly or suboptimal, and decided it would be a fun Friday afternoon task to make things a bit faster. With these changes along with a Rakudo scheduler patch I'm seeing at least 50% more requests per second..
> Assorted Cro::HTTP optimizations 

- lib/Cro/HTTP/Client.pm6
- t/http-client.t
Very often one only wants the response body and doesn't care about the
headers. However, today we make people write out this boilerplate:
my $response = await $client.get('http://foo.bar/baz');
my $body = await $response.body;
Provide a `get-body` convenience method, which reduces it to:
my $body = await $client.get-body('http://foo.bar/baz');
This is done for the other HTTP methods, except `HEAD`, since that is
explicitly requesting only the headers, so a `head-body` method would be
rather silly.
> Provide get-body and friends in Cro::HTTP::Client

- lib/Cro/HTTP/Router.pm6
- t/http-middleware.t
I recently helped track down a routing problem that was a result of
writing one `route` block inside another and forgetting the `include` or
`delegate` before it (it was actually an `openapi` block, but same
deal). Add a warning to provide a hint, rather that silently ignoring
those routes.
> Warn if a `route` block is sunk

- lib/Cro/HTTP/Middleware.pm6
`$connection-state.early-responses` is a live Supply and will stay alive in
memory unless we close it when we're done processing.
The leak can be reproduced with this Cro application:
```Raku
use Cro::HTTP::Server;
use Cro::Transform;
use Cro::HTTP::Request;
use Cro::HTTP::Response;
use Cro::HTTP::Middleware;
class Log does Cro::HTTP::Middleware::RequestResponse {
method process-requests(Supply $r) { $r }
method process-responses(Supply $r) { $r }
}
class MyApp does Cro::Transform {
method consumes() { Cro::HTTP::Request };
method produces() { Cro::HTTP::Response };
method transformer(Supply:D $pipeline --> Supply:D) {
supply {
whenever $pipeline -> $request {
my $response = Cro::HTTP::Response.new: :$request, :status(200);
$response.append-header('Content-Type: text/html'); …
```
> Fix Middleware::RequestResponse leaking a Supplier on every connection

- lib/Cro/HTTP/Cookie.pm6
- t/http-cookie.t
The cookie values are allowed to be wrapped in doublequotes, not in parentheses, d'uh.
See https://www.rfc-editor.org/rfc/pdfrfc/rfc6265.txt.pdf
The rule looks like:
```
cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
```
> Fix a misunderstanding of BNF syntax 4 years ago

- lib/Cro/HTTP/Router.pm6
- t/http-router.t
It turns out ACCEPTS could throw an exception instead of silently
returning False when it cannot unpack something.
It is an ambiguous error we should not show to the client, so
better hide it behind a 400, but in fact it can be a developer's
mis-understanding somewhere as well, so report them some info
that can be useful in debugging.
Tries to fix https://github.com/croservices/cro-http/issues/132
> Handle capture-related exceptions in request-body gracefully

- lib/Cro/HTTP2/FrameSerializer.pm6
The FrameSerializer must only mark the last partial frame as END_OF_STREAM
if the original non-split frame contained that flag.
Previous behaviour caused the marker to be sent twice if the conditions were right and
resulted in the remote end (rightfully) aborting the connection.
> Do not send the ENO_OF_STREAM flag twice

- lib/Cro/HTTP/Router.pm6
- t/http-router.t
`Cro::HTTP::Router::resource` calls `get-extension` to get the file extension of the requested resource, to guess at the MIME type.
But that sub doesn't return the extension, it returns the basename, so resources are always served an `application/octet-stream`.
This PR adds (initially failing) tests, and a fix for the code.
> Fix MIME type for `resource`

- lib/Cro/HTTP/MimeTypes.pm6
So this returns the proper 'application/wasm' type for web assembly file.
> Added webasm extension to MineType

- lib/Cro/HTTP/Cookie.pm6
- t/http-cookie.t
This provides an alternative fix to that one proposed in #174, which quieted a warning. Instead, this collects any extensions and makes them available (and fixes the warning along the way).
Also do a couple of other small code cleanups in the cookie handling code.
Update: now also handles #171.
> Assorted cookie improvements

- lib/Cro/HTTP2/ConnectionState.pm6
- lib/Cro/HTTP2/FrameSerializer.pm6
- lib/Cro/HTTP2/GeneralParser.pm6
The basic idea is to provide a mechanism of flow control back pressure, so
the remote end is not flooded with data it can't process fast enough.
The basic mechanism is as follows: We have a contingent of bytes we are
allowed to send in DATA frames to the remote party. If that contingent is
depleted we have to wait for the remote end to refresh it again via
WINDOW_UPDATE frames before we can continue to send more DATA frames.
> Implement remote window handling

- lib/Cro/HTTP/Client.pm6
- lib/Cro/HTTP2/GeneralParser.pm6
Cro::HTTP::Client::Pipeline2 relies on LAST to mark a connection as dead and thus not deadlocking when trying to use a dead connection. Without those two `LAST`s the `done` doesn't propagate up.
I'm not entirely sure why those two supply blocks need those while others don't (e.g. the tracer in in cro-core doesn't).
> Fix cleanup of timed out connections

- lib/Cro/HTTP/Client.pm6
It seems to have worked fine even without this change. Not sure entirely why the timeout didn't hit. But definitely correcter this way.
> Enable logic to prevent connection timeout

- META6.json
This fixes "Header table index 82 out of range" errors ocurring when using Cro::HTTP::Client with HTTP2 and multiple requests per connection.
> Bump HTTP::HPACK dep

- lib/Cro/HTTP/Client.pm6
- lib/Cro/HTTP2/GeneralParser.pm6
Remote side connection tear down (via a GoAway packet) and new requests are racey. If they collide the request fails. The user shouldn't be bothered to handle that case. Thus we automatically retry the request should a request fail as a result of a GoAway race condition.
Also GoAways are now communicated from the GeneralParser to HTTP::Client via Exceptions instead of a separate supply. This simplifies the interface.
Hint for testing this:
I used a local Apache webserver and introduced artificial latency on the loopback device via
tc qdisc add dev lo root netem delay 100ms
Then doing two consecutive requests on the same `Cro::HTTP::Client` object with a tuned sleep in between manages to hit the race condition.
> Implement a retry mechanism when GoAways are received

- lib/Cro/HTTP/Request.pm6
- t/http-request.t
Hi! I am really enjoying learning Cro. Thank you!
Missing Feature: HTTP/2 requests can send multiple Cookie headers. Cro::HTTP::Request will only check the first. This makes sense for HTTP/1.1 since it only allows one.
Solution: I checked the http-version string on unpack, to choose which behavior to use.
Motivation: I was trying to implement sessions and the request object kept losing my cookie, but not the CSRF cookie. After a lot of learning, I realized that browsers were sending multiple Cookie headers via HTTP/2. I saw this behavior with both Chrome and Safari.  When I set the Cro server to only accept 1.1, the browsers would only send 1 Cookie header, and the request object could parse it without issue.
[Relevant RFC Section](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.5) …
> Added support for HTTP/2 Cookie Headers

- lib/Cro/HTTP2/FrameParser.pm6
HTTP2 knows a stream and connection flow-control window. Both windows need to be respected. A logic was put in place, to not update the window sizes when the stream that sent the data was closed. That's fine. But we do need to update the global window, otherwise the global window size permanently shrinks by that amount. When reusing a connection many times, this shinks the window size down to zero over time, effectively stalling the connection.
> Fix HTTP2 connections with multiple streams stalling

- lib/Cro/HTTP/Client.pm6
HTTP1.1 connection reuse is subject to a race condition where remote connection tear down races with reusing the connection for a new request. This change wires HTTP1.1 into the same request retry mechanism HTTP2 uses.
HTTP2 was subject to the same race. I updated the PR respectively.
> Fix a connection reuse race

- Changes
- lib/Cro/HTTP2/FrameParser.rakumod
Avoid sending a window update frame with 0 bytes.
I think this is the cause of the issue in #203 introduced by #193
quoting https://medium.com/coderscorner/http-2-flow-control-77e54f7fd518
"WINDOW_UPDATE frame with a value 0 results in a stream error of type protocol error."
fixes [#203](https://github.com/croservices/cro-http/issues/203)
> Fix http2 window update
